version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: websocket-chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  chat-app:
    build: .
    image: websocket-chat-app:golang-v1.0
    restart: unless-stopped
    container_name: websocket-chat-app
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - APP_NAME=websocket-chat-app
    volumes:
      - ./ssl:/app/ssl:ro  # SSL sertifikalarını read-only olarak mount et
      - uploads:/app/uploads

volumes:
  redis_data:
  uploads:
volumes:
  redis_data:
  uploads:
  uploads:
